### PR TITLE
Added missing breadcrumb settings

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
PR looks good to me :+1: 

can yu please provide a before and after screenshot?

**Comment by OskarStark** [comment]
@core23 can you provide some screenshots?

**Comment by core23** [comment]
@OskarStark There is no change in the ui, so i couldn't give you a screenshot.
IMO it's a bug in the BlockService as the ``gallery`` / ``media`` parameter in a template wouldn't passed to this block (see: https://github.com/sonata-project/SonataSeoBundle/pull/99)

```twig
{{ sonata_block_render_event('breadcrumb', { 'context': 'gallery', 'current_uri': app.request.requestUri, gallery: 123 }) }}
```

**Comment by OskarStark** [comment]
Thank you for the feedback @core23 

i will merge this PR as it is :+1:

**Comment by core23** [comment]
Thank you ::smiley::

**Comment by OskarStark** [comment]
:smile: you're welcome! :+1: 

keep up the great work!

**Comment by Soullivaneuh** [comment]
Test should be added.

**Pull request merged**
