### PR TITLE
UI: Updated GalleryAdmin context picker

### PR DESCRIPTION
**Pull request by core23**
Before
bildschirmfoto 2015-11-30 um 13 53 26

After
bildschirmfoto 2015-11-30 um 14 16 28

### CODE REVIEW

**Comment by OskarStark** [comment]
i like this change

what about you @sonata-project/contributors

**Comment by core23** [comment]
Ping @rande @Soullivaneuh

**Comment by core23** [comment]
Ping @rande @greg0ire @Soullivaneuh

**Comment by greg0ire** [comment]
:+1:

**Comment by OskarStark** [comment]
i like it, too

**Comment by OskarStark** [comment]
thank you @core23

**Pull request merged**
