### PR TITLE
Composer fixes and improvements

### PR DESCRIPTION
**Pull request by Soullivaneuh**
**THIS BUNDLE WILL HAVE A NEW MAJOR RELEASE**

* 3.x-dev
* Use new composer constraints notation
* Remove minimum-stability option to clearly show which required packages are not stable

### CODE REVIEW

**Comment by nicolasricci** [comment]
why not taking this opportunity to update to `knplabs/gaufrette: "^0.2"`?

**Comment by Soullivaneuh** [comment]
@nicolasricci Not the goal of this PR.

Feel free to open another one once this one merged. :+1:

**Comment by kvdnberg** [comment]
Any ideas on when this will be merged? I wanted to test the media bundle in a Symfony 3 project but I can't install dev-master now due to the non-existent classification bundle required version.

**Comment by Soullivaneuh** [comment]
> Any ideas on when this will be merged?

Quick answer: ASAP.

I'm working on those bundles on my fee time so I'm not able to give you an ETA right now.

**Pull request merged**
