### PR TITLE
Fixed andFlush parameter in MediaManager never being used. Based on #537

### PR DESCRIPTION
**Pull request by prashantpalikhe**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Having unit test that reveal the concerned would be useful. Can you please consider it?

**Comment by prashantpalikhe** [comment]
Don't have much experience there. May be somebody else could pitch in?

**Comment by Soullivaneuh** [comment]
Maybe @Uriziel?

**Comment by Uriziel** [comment]
Give me an hour.

**Comment by Soullivaneuh** [comment]
> Give me an hour.

You have all the time you want @Uriziel! ;-)

**Comment by Uriziel** [comment]
@Soullivaneuh #797

**Pull request closed without merging**
