### PR TITLE
Composer improvements

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added compatibility with Gaufrette `^0.4` and `^0.5`
- Added compatibility with Buzz `^0.16`

### Removed
- Removed compatibility with Gaufrette `^0.1`and `^0.2`
- Removed compatibility with JMS serializer `^0.13`
```

## Subject

A few changes on composer, this was by far the hardest repo to update:

- Up some sonata dependencies
- Add missing symfony dependencies
- Replace `security` by `security-core` on required section and `security-csrf` on required-dev section (only used in tests)
- Removed deprecated Amazon dependency: only used in tests.
- Upgrade Gaufrette (allow 0.4 and 0.5 and remove 0.1 and 0.2) 
- Upgrade serializer (remove 0.13)
- Upgrade Buzz (add 0.16)
- Upgrade phpunit-bridge

There is a missing thing:

- Allow aws ^3.0. This will be done in another PR because it will need some update on our code and it was too much already for this PR.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Can you check travis?

**Comment by jordisala1991** [comment]
Done, fixed (I hope)

**Comment by kunicmarko20** [comment]
:disappointed:

**Comment by jordisala1991** [comment]
It is now. Travis don't you dare failing again

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !

**Comment by Soullivaneuh** [comment]
Dropping version support is a minor.

**Pull request merged**
