### PR TITLE
Set sonata.media.pool service as public

### PR DESCRIPTION
**Pull request by tifabien**
## Subject

Needed because of the InlineValidator in form-extension repo (See https://github.com/sonata-project/form-extensions/blob/master/src/Validator/InlineValidator.php#L53).

I am targeting this branch, because only applicable on master.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Can you point how we end up requesting `sonata.media.pool` on the inlineValidator from `form-extension`?

**Comment by tifabien** [comment]
`sonata.media.pool` is requested in https://github.com/sonata-project/SonataMediaBundle/blob/master/src/Resources/config/validation.xml#L5

Because we pass a string to the inlineValidator it tries to fetch the service from the container.

**Review by VincentLanglet — APPROVED** [review]
Maybe we should create an issue to change to way this constraint works by using dependency injection instead ?

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @tifabien

**Pull request merged**
