### PR TITLE
Used find method to get entity by ID

### PR DESCRIPTION
**Pull request by spolischook**

### CODE REVIEW

**Comment by spolischook** [comment]
In my own environment tests, version with `find` is 10% faster then `findOneById`

**Comment by spolischook** [comment]
@soullivaneuh please consider significant performance improvement with no BC

**Comment by OskarStark** [comment]
Can you share a Blackfire profile please?

**Comment by spolischook** [comment]
`find($id)` Wall time 1.22s:
https://blackfire.io/profiles/4c18dc76-276e-4ffb-80fa-e80a0fc8b7f8/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()
`findOneBy(['id' => $id])` Wall time 1.56s:
https://blackfire.io/profiles/427b3c4d-082a-4a0d-9f11-bdda927dadbd/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

**Comment by OskarStark** [comment]
@greg0ire please give us a final review here and merge, thanks 👍

**Comment by greg0ire** [comment]
Thanks @spolischook !

**Pull request merged**
