### PR TITLE
unified closing xml tag

### PR DESCRIPTION
**Pull request by OskarStark**
Make sure we have a whitespace before `/>`

Maybe we could check this with a linter or sth like StyleCI?

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire can you please give me a review?

**Comment by greg0ire** [comment]
RTM

**Comment by Soullivaneuh** [comment]
> Make sure we have a whitespace before `/>`

Why? Is that on any convention?

> Maybe we could check this with a linter or sth like StyleCI?

We can't, StyleCI checks only PHP file.

But if you have a good xml linter tools to told to me, open an issue on dev-kit and I will integrate it. :+1:

**Comment by greg0ire** [comment]
`xmllint --format` is not on your side @OskarStark :

```
xmllint --format /tmp/test.xml 
<?xml version="1.0" encoding="UTF-8"?>
<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
  <services>
    <service id="sonata.media.notification.create_thumbnail" class="Sonata\MediaBundle\Consumer\CreateThumbnailConsumer">
      <tag name="sonata.notification.consumer" type="sonata.media.create_thumbnail"/>
      <argument type="service" id="sonata.media.manager.media"/>
      <argument type="service" id="sonata.media.pool"/>
      <argument type="service" id="service_container"/>
    </service>
    <service id="sonata.media.thumbnail.consumer.format" class="Sonata\MediaBundle\Thumbnail\ConsumerThumbnail">
      <argument>sonata.media.thumbnail.format</argument>
      <argument type="service" id="sonata.media.thumbnail.format"/>
      <argument type="service" id="sonata.notification.backend"/>
      <argument type="service" id="event_dispatcher"/>
    </service>
  </services>
</container>

```

**Comment by OskarStark** [comment]
> Why? Is that on any convention?

Don't know, but mixing stuff in the same file is not so nice, but I am free to dicuss it

**Comment by greg0ire** [comment]
But maybe have a look at symfony ?

**Comment by OskarStark** [comment]
> xmllint --format is not on your side @OskarStark :

didn't know that @greg0ire but the current status with mixed stuff is gainst everything... readability... diffs...

We should keep only with or without a space

**Comment by Soullivaneuh** [comment]
> Don't know, but mixing stuff in the same file is not so nice, but I am free to dicuss it

I would like a tool for that, so no mixing stuff.

So I would prefer to not merge this PR for the moment.

If the linter do the reverse, it would be stupid. :wink:
 
https://github.com/sonata-project/dev-kit/issues/139

**Comment by OskarStark** [comment]
> So I would prefer to not merge this PR for the moment.

👍

**Comment by Soullivaneuh** [comment]
See #1046.

**Pull request closed without merging**
