### PR TITLE
Update LiipImagineThumbnail.php

### PR DESCRIPTION
**Pull request by gonzalovilaseca**
Adjusted routing to latest LiipImagine

### CODE REVIEW

**Comment by rande** [comment]
@gonzalovilaseca we need to support the old version. Can you find a way to make the code BC ? Thanks

**Comment by pyrech** [comment]
Any news on this issue?

In my case, reference images have a wrong  url (missing `/media` prefix) while others filtered images are fine =/

**Comment by sfavot** [comment]
up ?

**Comment by gonzalovilaseca** [comment]
I'll have a look during this week, will update PR when I fin a BC solution.

**Comment by phansys** [comment]
@gonzalovilaseca, I think in order to be BC, you could try with something like:
```php
if ($this->router->getRouteCollection()->get('liip_imagine_filter')) {
    // ... new way
} else {
    // ... old way
}
```

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by OskarStark** [comment]
@core23 I guess we should reopen and apply this PR against 3.x, WDYT?

**Comment by afranioce** [comment]
This PR resolve integration with liipimagine 2.x

**Comment by core23** [comment]
Can you create a new PR with a fix @afranioce ?

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataMediaBundle/issues/1416

**Pull request closed without merging**
