### PR TITLE
Fix definition of MediaRuntime

### LINKED ISSUE #2148: Sonata\MediaBundle\Twig\Extension\MediaRuntime
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
sonata-project/admin-bundle              3.86.0 4.0.1  The missing Symfony Admin Generator
sonata-project/block-bundle              3.23.2 4.7.0  Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
sonata-project/doctrine-extensions       1.14.0 1.14.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.26.0 4.0.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.8.0  2.8.0  Lightweight Exporter library
sonata-project/form-extensions           1.11.0 1.11.0 Symfony form extensions
sonata-project/media-bundle              3.34.0 3.34.0 Symfony SonataMediaBundle
sonata-project/translation-bundle        2.8.1  2.9.0  SonataTranslationBundle
sonata-project/twig-extensions           1.9.0  1.9.0  Sonata twig extensions

```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.2 (cli) (built: Feb  1 2020 19:47:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

```

## Subject

twig.xml refer to a service class Sonata\MediaBundle\Twig\Extension\MediaRuntime it should be Sonata\MediaBundle\Twig\MediaRuntime

## Steps to reproduce

Load the admin on a edit of a medi

## Expected results

Working

## Actual results

Unable to load the "Sonata\MediaBundle\Twig\MediaRuntime" runtime.

## Note

There is a lack of integration testing in all sonata bundle. I catch those errors by just having the symfony crawler loading the admin in a automation test.

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #2148

## Changelog

```markdown
### Fixed
- Fixed MediaRuntime definition.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Does it fix your issue? @mpoiriert

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by haivala** [comment]
Changed
`{%media item.picture, 'big' with {'class':'img-fluid'}%}`
To
`{{ sonata_media(item.picture, 'big', {'class':'img-fluid'}) }}`

And now I get `An exception has been thrown during the rendering of a template ("The identifier id is missing for a query of App\Entity\SonataMediaMedia").`

**Comment by haivala** [comment]
ah! now we need to test if `item.picture` exits

**Comment by haivala** [comment]
and the output is not and picture. it is the html for it. raw filter missing

**Pull request merged**
