### PR TITLE
Add getName on blocks for SonataPageBundle

### LINKED ISSUE #1962: Blocks don't have name in SonataPageBundles composer
#### Sonata packages

<details><summary>show</summary>
<p>

```
sonata-project/admin-bundle              3.100.2 3.100.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.23.1  4.6.0   Symfony SonataBlockBundle
sonata-project/cache                     1.1.1   2.1.1   Cache library
sonata-project/cache-bundle              2.4.2   3.3.0   This bundle provides caching services
sonata-project/datagrid-bundle           3.3.0   3.3.0   Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.12.0  1.12.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.34.1  3.34.1  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2   2.6.2   Lightweight Exporter library
sonata-project/form-extensions           1.9.0   1.9.0   Symfony form extensions
sonata-project/formatter-bundle          4.5.0   4.5.0   Symfony SonataFormatterBundle
sonata-project/media-bundle              3.31.2  3.31.2  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.12.0  3.12.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.22.2  3.22.2  This bundle provides a Site and Page management through container and block ser...
sonata-project/seo-bundle                2.13.0  2.13.0  Symfony SonataSeoBundle
sonata-project/twig-extensions           1.6.0   1.6.0   Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
symfony/asset                      v5.2.7  v5.2.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScri...
symfony/cache                      v5.2.9  v5.2.9  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v4.4.23 v5.2.8  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v4.4.24 v5.2.8  Eases the creation of beautiful and testable command line interfaces
symfony/debug                      v4.4.22 v4.4.22 Provides tools to ease debugging PHP code
symfony/debug-bundle               v5.1.11 v5.2.4  Provides a tight integration of the Symfony Debug component into the Symfony full-sta...
symfony/debug-pack                 v1.0.9  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.24 v5.2.9  Allows you to standardize and centralize the way objects are constructed in your appl...
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.24 v5.2.9  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v4.4.20 v5.2.4  Registers environment variables from a .env file
symfony/error-handler              v4.4.23 v5.2.8  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.20 v5.2.4  Provides tools that allow your application components to communicate with each other ...
symfony/event-dispatcher-contracts v1.1.9  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.7  v5.2.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v4.4.22 v5.2.7  Provides basic utilities for the filesystem
symfony/finder                     v5.2.9  v5.2.9  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.13.3 v1.13.3 Composer plugin for Symfony
symfony/form                       v4.4.24 v5.2.9  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.24 v5.2.9  Provides a tight integration between Symfony components and the Symfony full-stack fr...
symfony/google-mailer              v4.4.20 v5.2.4  Symfony Google Mailer Bridge
symfony/http-client                v4.4.24 v5.2.9  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.23 v5.2.8  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.24 v5.2.9  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.2.7  v5.2.7  Provides a PHP replacement layer for the C intl extension that includes additional da...
symfony/mailer                     v4.4.22 v5.2.7  Helps sending emails
symfony/maker-bundle               v1.31.1 v1.31.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and m...
symfony/mime                       v5.2.9  v5.2.9  Allows manipulating MIME messages
symfony/monolog-bridge             v4.4.22 v5.2.7  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v4.4.20 v5.2.4  Provides an improved replacement for the array_replace PHP function
symfony/orm-pack                   v1.1.0  v2.1.0  A pack for the Doctrine ORM
symfony/polyfill-ctype             v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.0 v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.0 v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.22 v5.2.7  Executes commands in sub-processes
symfony/profiler-pack              v1.0.5  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v5.2.4  v5.2.4  Provides functions to read and write from/to an object or array using a simple string...
symfony/property-info              v5.2.8  v5.2.8  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                    v4.4.24 v5.2.9  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.2  v3.1.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.23 v5.2.9  Provides a tight integration of the Security component into the Symfony full-stack fr...
symfony/security-core              v4.4.24 v5.2.9  Symfony Security Component - Core Library
symfony/security-csrf              v5.2.7  v5.2.7  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.23 v5.2.8  Symfony Security Component - Guard
symfony/security-http              v4.4.24 v5.2.9  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.7  v5.2.7  Provides a way to profile code
symfony/string                     v5.2.8  v5.2.8  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points an...
symfony/templating                 v4.4.20 v5.2.4  Provides all the tools needed to build any kind of template system
symfony/translation                v4.4.24 v5.2.9  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.22 v5.2.8  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.24 v5.2.9  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v4.4.24 v5.2.9  Provides tools to validate values
symfony/var-dumper                 v5.2.8  v5.2.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.2.8  v5.2.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v5.0.11 v5.2.8  Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.11.2 v1.11.2 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.24 v5.2.9  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.19 (cli) (built: May  6 2021 22:27:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies
```

## Subject
Blocks don't have name in SonataPageBundles composer

## Steps to reproduce
Install
use SonataPageBundles composer to select blocks
## Expected results
Blocks should have names
## Actual results
Blocks are missing getName() method so for example
```   
public function getName()
{
        return 'Media Block';
}
```
Should be added

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #1962 .

## Changelog

```markdown
### Added
- Added name for blocks so they can be recognized on SonataPageBundle.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
@haivala does this fixes your issue?

**Comment by VincentLanglet** [comment]
This method was deprecated from the interface https://github.com/sonata-project/SonataBlockBundle/blob/b161b8273366bec8d878e8e5a5c91a270eba3aa2/CHANGELOG.md#deprecated-2

So it require a NEXT_MAJOR to remove them in master. (And I don't know how it will be handle by the PageBundle)

**Comment by jordisala1991** [comment]
> This method was deprecated from the interface https://github.com/sonata-project/SonataBlockBundle/blob/b161b8273366bec8d878e8e5a5c91a270eba3aa2/CHANGELOG.md#deprecated-2
> 
> So it require a NEXT_MAJOR to remove them in master. (And I don't know how it will be handle by the PageBundle)

Added NEXT_MAJOR comment. On SonataPageBundle 4.x it will be handled using https://github.com/sonata-project/SonataMediaBundle/blob/master/src/Block/FeatureMediaBlockService.php#L104-L109
already implemented on all blocks.

**Review by VincentLanglet — APPROVED** [review]

**Comment by haivala** [comment]
> @haivala does this fixes your issue?

Yes! Thank you!

**Pull request merged**
