### PR TITLE
Updated cs-fixer

### PR DESCRIPTION
**Pull request by core23**
Somehow my first commit (https://github.com/sonata-project/SonataMediaBundle/pull/900) got broken, so here it is again 

Use same settings from https://github.com/sonata-project/SonataAdminBundle/blob/master/.php_cs

### CODE REVIEW

**Comment by rande** [comment]
Weird, I want thinking @Soullivaneuh already did it on MediaBundle ;)

**Comment by core23** [comment]
No, the cs-fixer settings are different on some other sonata bundles

**Comment by rande** [comment]
@core23 I guess the SonataCoreBundle should be the base for others ...  @Soullivaneuh  ?

**Comment by OskarStark** [comment]
:+1:  for CoreBundle

**Comment by Soullivaneuh** [comment]
I guess that such config should be grouped on a single package, dedicated for this thing (sonata-project/contributing, sonata-project/dev-tools|env...).

I can work on it when this PR will be reviewed: https://github.com/sonata-project/SonataAdminBundle/pull/3273 :+1:

**Comment by OskarStark** [comment]
sounds great @Soullivaneuh

**Comment by OskarStark** [comment]
for now we should merge this change IMO

**Comment by OskarStark** [comment]
ping @sonata-project/contributors

**Pull request merged**
