### PR TITLE
Fixed andFlush parameter in MediaManager never being used.

### PR DESCRIPTION
**Pull request by Uriziel**

### CODE REVIEW

**Comment by Guere** [comment]
I just ran into this bug while working on a batch script during which I would prefer not to flush during each save. After some searching I landed here.

I see the automated builds failed after this patch was submitted. Perhaps someone with more knowledge of the situation can look into this, and finally include this patch.

**Comment by Uriziel** [comment]
The patch is OK, builds failed because of stuff unrelated to them.

**Comment by prashantpalikhe** [comment]
How can we get this patch merged then? Quite a big bug just lingering around for years :)

**Comment by Soullivaneuh** [comment]
> The patch is OK, builds failed because of stuff unrelated to the changes.

@Uriziel Please rebase your PR to make it working with the new Travis configuration.

**Comment by Uriziel** [comment]
I can't rebase it any more as I deleted the repository. Feel free to redo the patch on your own patch though.

**Comment by Soullivaneuh** [comment]
Seems @prashantpalikhe done it on #796. Closing this one. Thanks.

**Pull request closed without merging**
