### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by greg0ire**
Manual merge

### CODE REVIEW

**Comment by OskarStark** [comment]
Why is travis failing? 🤔

**Comment by jordisala1991** [comment]
It is not suposed to have SF 2.3 2.7 on travis, this is master

**Comment by greg0ire** [comment]
Because we are requiring 2.8 but a 2.3 build appeared I guess. Let's remove it.

**Comment by greg0ire** [comment]
Wow there is automatic dismissal of reviews now?

**Pull request merged**
