### PR TITLE
Added CloudFrontClient type hint

### PR DESCRIPTION
**Pull request by core23**
Closes #

### Changelog

```markdown
### Changed
- Changed `CloudFrontClient::setClient` signature to accept only `CloudFrontClient`
```

### Subject
Removed deprecation on `CloudFrontClient::setClient` method

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @core23 i scheduled this for 3.0 can you please refer the PR where we introduced the ``trigger_error``?

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by core23** [comment]
Please review @sonata-project/contributors

**Comment by greg0ire** [comment]
LGTM

**Pull request merged**
