### PR TITLE
remove not used file Model.GalleryHasMedia.xml file

### PR DESCRIPTION
**Pull request by OskarStark**
I am targetting this branch, because i forgot to remove the file in a BC break PR which is already merged.

Refs #948

## Changelog

```markdown
### Removed
- Removed `Resources/config/serializer/Model.GalleryHasMedia.xml`
```

## Subject

The file is not needed anymore, `Resources/config/serializer/Model.GalleryItem.xml` is used instead.

### CODE REVIEW

**Comment by core23** [comment]
The file `Model.GalleryItem.xml` doesn't exists. You should rename the old file instead of removing it.

**Comment by OskarStark** [comment]
> The file Model.GalleryItem.xml doesn't exist. You should rename the old file instead of removing it.

really? on my machine it is available 😕 

bildschirmfoto 2016-08-03 um 14 37 58

**Comment by core23** [comment]
Have a look at github: https://github.com/sonata-project/SonataMediaBundle/tree/master/Resources/config/serializer

**Comment by OskarStark** [comment]
don't understand

bildschirmfoto 2016-08-07 um 15 46 33

`Model.GalleryItem.xml` exists in your link 😕

**Comment by core23** [comment]
Forget my last comment. Just arrived from Wacken 😆

**Comment by OskarStark** [comment]
> Forget my last comment. Just arrived from Wacken 😆

😄

**Pull request merged**
