### PR TITLE
Sync thumbnails command optimization

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
I encountered such problem - when trying to sync large amount of thumbnails (6000+) command gets aborted by memory limit, cause it fetches all medias at once in one batch. This PR introduces medias processing in batches (batch size can be changed via --batchSize option and equals to 100 by default). So now this command can process as many thumbnails, as we have.

### CODE REVIEW

**Comment by rande** [comment]
@MAXakaWIZARD I think you can also clear the Doctrine Unit Of Work. This will save more memory.

**Comment by MAXakaWIZARD** [comment]
@rande Yep, working on this at the moment.

**Comment by MAXakaWIZARD** [comment]
@rande This doesn't work (memory consumption increases with each batch):
```php
$this->getContainer()->get('doctrine')->getManager()->clear();
```
Does sonata media use different entity manager (non-default)?

**Comment by MAXakaWIZARD** [comment]
This returns true for each media, so this is right entity manager:
```php
$this->getContainer()->get('doctrine')->getManager()->contains($media);
```

**Comment by MAXakaWIZARD** [comment]
As I see, memory leak is somewhere in those calls (cause if I comment them out, memory usage is stable and is not growing):
```php
$provider->removeThumbnails($media);
$provider->generateThumbnails($media);
```

**Comment by rande** [comment]
The generateThumbnails does not create state variables, so it either a leak in the gd lib, or a variable reference somewhere.

**Comment by MAXakaWIZARD** [comment]
@rande problem is in `Gaufrette\Filesystem` - it stores all files in `fileRegister` and it never gets cleared, and there is no method for that. Since it holds files with content, it runs out of memory pretty fast.
I see such solutions:
1) extend `Gaufrette\Filesystem` class with `clear` method and call it after each resize
2) try to contribute to `Gaufrette` and introduce that method

**Comment by rande** [comment]
@MAXakaWIZARD option 3 ... use the reflection api to make the property public and clear the array ...

**Comment by MAXakaWIZARD** [comment]
@rande not very good, but is OK as a temporary solution

**Comment by rande** [comment]
you need to do that in the command only, you can add a big notice about the issue.

**Comment by MAXakaWIZARD** [comment]
Implemented those methods here: https://github.com/KnpLabs/Gaufrette/pull/329
Will do temporary workaround since that PR may not be merged for months.

**Comment by MAXakaWIZARD** [comment]
Fixed those issue.
But we have another one)
When one format gets removed from context in config, sync-thumbnails does not delete old thumbnails in old formats. I think we need delete all files matching this mask: `thumb_{mediaId}_*.*`

**Comment by rande** [comment]
I think this require a dedicated command to remove a specific format.

**Comment by MAXakaWIZARD** [comment]
@rande Good idea. I will do that in another PR. Could you please merge this?

**Comment by MAXakaWIZARD** [comment]
I think this PR can be closed now...

**Comment by rande** [comment]
@MAXakaWIZARD the PR is closed as I merged it

**Pull request merged**
