### PR TITLE
 medias are not filtered by category 

### LINKED ISSUE #1054: medias are not filtered by category
Medias are not filtered by category

| Question | Answer |
| --- | --- |
| Bundle version | 3.x |
| Symfony version | 2.8 |
| php version | 5.5 |
# Steps to reproduce

create medias and assign different categories
# Expected results

Only medias of the current category are visible
# Actual results

All medias are visible

### PR DESCRIPTION
**Pull request by huziatwork**
Closes #1054 

### Changelog

```markdown
### Fixed
- Medias are not filtered by category

### Changed
- Changed datagrid value of category from object to id of category
```

### CODE REVIEW

**Comment by OskarStark** [comment]
@ahmetakbn can you please have a look at this PR?

If I am right, you changed it a few weeks ago to object instead of id

**Comment by ahmetakbn** [comment]
> @ahmetakbn can you please have a look at this PR?
If I am right, you changed it a few weeks ago to object instead of id

Yes I changed it

**Comment by ahmetakbn** [comment]
@huziatwork there is no filter for category in the default behavior of 'SonataMediaBundle' please check here: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Admin/ORM/MediaAdmin.php#L40

I don't know how you are filtering the Medias by category. In any case, can you please try to remove media files from the list view by choosing them with check option. Try to delete them without clicking filter button.

**Comment by huziatwork** [comment]
@ahmetakbn I'm filtering by clicking on a category in the category tree on the left side. 

Following tests where successfully
- delete a single media in the edit view
- delete a single media in the list overview (selecting by checkbox)
- delete all medias in the list overview (checkbox "all elements")
- delete some medias  (selecting them by checkbox) in the list view

**Comment by ahmetakbn** [comment]
@huziatwork To reproduce this deletion problem, you should have your media files related to an entity. Can you also make this sure?

Here is a full deletion issue reproducing on the list view:
- Create media files and relate them to entities
- Go to list view of medias
- Without filtering select by check box and delete

**Comment by huziatwork** [comment]
I found an additional error. Clicking on Medias on the side menu did not work (no "category" in the URL). I fixed this by changing MediaAdminController.php.

@ahmetakbn Deleting a Media which is related to a Gallery from the list view does not work. I get an Integrity constraint violation. Without my changes I get the same error. But I think this problem is not related to this bug, because trying to delete the Media in the Edit view also does not work.

**Comment by OskarStark** [comment]
@ahmetakbn can you please link your PR here, IMO this PR is a revert of yours!

**Comment by ahmetakbn** [comment]
> @ahmetakbn can you please link your PR here, IMO this PR is a revert of yours!

Yes it is definitely a revert of my PR. Here it is: #996

**Comment by ahmetakbn** [comment]
@huziatwork If you are getting Integrity constraint violation error also while trying to delete the object on Edit view, you can not reproduce the deletion issue which I mentioned. Can you please add this ORM annotation to your relation:
```
@ORM\JoinColumn(onDelete="SET NULL")
```
This should prevent the error you get while deleting object. Please make it sure that you don't get any error while deleting object on Edit view. If you succeeded to delete object on Edit view, please try to reproduce the deleting problem on the list view again. 
After your changes, I go to media list, select a context, click just once to filter button and try to delete medias on list. I got the a success message after deleting object on the list view but the media file is still there. 
The full relation of media file to my entity is like this:
```
/**
 * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", cascade={"persist", "remove"})
 * @ORM\JoinColumn(onDelete="SET NULL")
 */
```
Can you please try once more, thanks.

**Comment by huziatwork** [comment]
@ahmetakbn I added the '@ORM\JoinColumn(onDelete="SET NULL")' annotation to my entites. 
I got no error messages and all medias where deleted. I also tested the case with filtering by context -> no error message.

**Comment by OskarStark** [comment]
Stuck build @Soullivaneuh

**Comment by core23** [comment]
Can you please rebase to retrigger the build @huziatwork

**Comment by huziatwork** [comment]
Rebased PR #1129

**Pull request closed without merging**
