### PR TITLE
Added missing id getters

### PR DESCRIPTION
**Pull request by core23**
### Changelog

```markdown
### Added
- Added missing `GalleryHasMediaInterface::getId` method
- Added missing `GalleryInterface::getId` method
```

### Subject

Added missing id getters to model classes

### To do
- [x] Add an upgrade note

### CODE REVIEW

**Comment by OskarStark** [comment]
This should be implemented in next major

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by OskarStark** [comment]
This is for the next major

**Comment by OskarStark** [comment]
@core23 can you please add the PR header?

**Comment by core23** [comment]
Done @OskarStark

**Comment by OskarStark** [comment]
Thank you @core23 

can you please give us a final review?

**Comment by greg0ire** [comment]
What makes these method "missing". Which class needs them to be present?

**Comment by core23** [comment]
They are not needed in this bundle, but other bundles need this getters, e.g. https://github.com/sonata-project/SonataNewsBundle/blob/645b8f85e48a658d10d24214db090195b7e71409/Entity/PostManager.php#L147

**Comment by core23** [comment]
RTM? @greg0ire @OskarStark

**Comment by greg0ire** [comment]
Thanks @core23 !

**Pull request merged**
