### PR TITLE
Ensure ClassificationBundle related entities (Categories & Cie) are refreshed after a ObjectManager#clear

### PR DESCRIPTION
**Pull request by lemoinem**
This fixes sonata-project/SonataClassificationBundle#60

The issue wasn't reported in MediaBundle because the error is reported on ClassificationBundle Entities.

I didn't find any test on the Doctrine Listeners, so I didn't add new tests.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can you summary the solved issue by this PR and exactly which steps to do for reproduce it?

**Comment by rande** [comment]
@lemoinem maybe you can try to add unit test ;)

**Comment by lemoinem** [comment]
Hello,

Thanks for the fast follow up...

Issue:
If an `ObjectManager` is cleared after the root categories have been loaded by the `MediaEventSubscriber`, the (now detached) categories and contexts will be reused without being refreshed/merged. This triggers a dirty+managed state for the `Context`/`Category` and an error when a media referring it is persisted/flushed.

Steps to reproduce:
0. Initialize the `MediaBundle`, load required `Category`s and `Context`s, etc.

In a single PHP function:
1. Create, Persist and Flush a new `Media` **A** (`Context` and `Provider` are irrelevant)
2. Clear the `ObjectManager`
3. Create, Persist and Flush a new `Media` **B** (`Context` and `Provider` are also irrelevant).

Expected Behavior:
  The two `Media`s are persisted in database without error.

Current Behavior:
  When the second `Media` is persisted/flushed an exception is thrown with the message: "A managed+dirty entity CONTEXT_NAME can not be scheduled for insertion."

**Comment by Soullivaneuh** [comment]
> @lemoinem maybe you can try to add unit test ;)

@lemoinem Could you do that?

**Comment by rande** [comment]
@lemoinem this one is a tricky one. I remember having this once, but cannot reproduce it ...

**Comment by lemoinem** [comment]
As mentioned there are currently no Unit Test at all for the Listener. Sure, I could try to add Unit Tests, but I didn't for two reasons:
1. This is more an integration than a unit feature issue 
2. Adding complete new tests to cover the Listeners seem to be a different issue entirely which would be worth its own PR.

This said, if you wish me to provide regression tests for this specific issue, I could try to. But I've never created Integration/Regression tests for a Symfony Bundle and I'm not sure how long it could take me to do so...

**Comment by lemoinem** [comment]
@rande @Soullivaneuh 
Ok, I created a Unit Test for the bug. I did check the test fails with the current version and pass with my fix.

**Comment by rande** [comment]
@lemoinem thanks for the tests, however you need to code with the old school syntax of php 5.3

**Comment by lemoinem** [comment]
@rande, Here is the PHP5.3 version. Since Symfony is PHP5.4+ now anyway, I thought it applied to the bundles too. My bad.

**Comment by Soullivaneuh** [comment]
> Since Symfony is PHP5.4+

Where did you see that? This is wronk AFAIK: https://github.com/symfony/symfony/blob/a44ceb3156e549ffc17baaab7a206be39b636d4f/composer.json#L19

**Comment by lemoinem** [comment]
Oh, looks like I got confused. 5.3 did reach EOL, but symfony still support it. I thought they droped support for 5.3 when it reached EOL.

Sorry about this. Thanks for your patience.

**Comment by lemoinem** [comment]
@rande: The travis build fails because of memory limitations, this is unrelated to my modifications.

**Comment by lemoinem** [comment]
@rande Any news on this? It seems to have been ready to be merged for more than a month...

**Comment by ksom** [comment]
:+1:

**Comment by lemoinem** [comment]
This has been ready to be merged for quite some time now. Any news @rande @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
@lemoinem please rebase your PR to make Travis green.

**Comment by lemoinem** [comment]
@Soullivaneuh @rande Rebasing done.
Scrutinizer, SonataCI - Quick Check and travis are green :green_heart: now...

Regarding travis, PHP7 and hhvm fail because of a missing Mongo PHP extension, this is unrelated to my modifications. Build using Symfony 3.0 fails because of an undefined method in a Mock on (deprecated, remove in Symfony 3.0) SecurityContextInterface, this is unrelated to my modifications.

The failed Sandbox checks do not provide any details, so I don't know what to fix...

**Comment by lemoinem** [comment]
In the mean time, for hte ones hitting this bug, You can use this service workaround:
https://gist.github.com/lemoinem/5497d46df74ac9a9df14

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
