### PR TITLE
Upgrade Sonata to v4

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC break

Not closing issues but there are some PRs with some of this code.

## Changelog

```markdown
### Added
- Add Compatibility with Sonata 4.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
```
1) Sonata\MediaBundle\Tests\Provider\BaseProviderTest::testBuildEditForm
Undefined index: translation_domain

/home/runner/work/SonataMediaBundle/SonataMediaBundle/vendor/sonata-project/admin-bundle/src/Form/FormMapper.php:118
/home/runner/work/SonataMediaBundle/SonataMediaBundle/tests/Provider/BaseProviderTest.php:190
/home/runner/work/SonataMediaBundle/SonataMediaBundle/tests/Provider/AbstractProviderTest.php:77
```

A lot of this errors appear. @VincentLanglet can you help me? This comes from the admin-bundle, not sure if a bug or I am missing something.

**Comment by VincentLanglet** [comment]
I would change
```
if ($group['translation_domain'] && !isset($fieldDescriptionOptions['translation_domain'])) {
    $fieldDescriptionOptions['translation_domain'] = $group['translation_domain'];
}
```
to
```
if (isset($group['translation_domain']) && !isset($fieldDescriptionOptions['translation_domain'])) {
     $fieldDescriptionOptions['translation_domain'] = $group['translation_domain'];
}
```
(or `isset($group['translation_domain']) && $group['translation_domain']`)

Can you try it ?

**Comment by jordisala1991** [comment]
Solved by not mocking the admin.

**Comment by jordisala1991** [comment]
Needs: https://github.com/sonata-project/dev-kit/pull/1558

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
