### PR TITLE
Remove imagine/imagine old version 0.7

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Removed
- testing in CI use imagine version 0.7
```

### CODE REVIEW

**Comment by Yozhef** [comment]
Change in Dev kit -> https://github.com/sonata-project/dev-kit/pull/1475

**Comment by Yozhef** [comment]
@jordisala1991 done =)

**Review by VincentLanglet — DISMISSED** [review]

**Review by wbloszyk — DISMISSED** [review]

**Comment by wbloszyk** [comment]
@Yozhef Can you also remove it from composer?

**Comment by jordisala1991** [comment]
We do not test all posible versions with the dev-kit variants. Imo it can be removed from dev-kit and from composer.json at a separate steps.

**Review by jordisala1991 — DISMISSED** [review]

**Comment by Yozhef** [comment]
@wbloszyk  yes but it hasn't resulted in yet to be created BREAKING CHANGE because maybe some projects use 0.7 and pulling up changes will fail.

**Comment by Yozhef** [comment]
@jordisala1991 I can delete from the composer by a separate request?

**Comment by jordisala1991** [comment]
Do not worry with this PR, because dev-kit will update that file instead, there are some more files to be updated. If later you want to change composer, you can do it.

**Comment by jordisala1991** [comment]
Already merged

**Pull request closed without merging**
