### PR TITLE
Open-source development monetization

### PR DESCRIPTION
**Pull request by PatchRanger**
I am targeting this (`master`) branch, because in my view it looks like major change.

## Changelog

```markdown
### Added
- Open-source development monetization by pay-or-wait algorithm
```

## To do

- [ ] Please review whether it correponds to your vision of the open-source development

## Subject

In short: this PR proposes a way to monetize open-source development of your project.

The idea is similar to how free-to-play works in gamedev industry: "You are free to wait for the package download - but in case if time is money for you, please consider buying non-waiting access to the package, every cent goes to the package developer to incentive the open-source development."

For details please refer to https://github.com/Free2Wait/composer-free2wait .

According to packagist statistics of your package https://packagist.org/packages/sonata-project/media-bundle/stats , in theory it could bring to you about 21,540 (installs per month) * 0.03 (estimated conversion installs-to-sale) * 5 (price of each non-waiting access per month) = estimated $3,231 per month.

Please do not consider it as ready-to-merge PR, it's work-in-progress: I am just willing to get your potentional or conditional (what is needed to make it suitable) consent to merge it in the future. There are already several issues/concerns (see https://github.com/Free2Wait/composer-free2wait/issues).

Please give me your feedback about the idea: what do you think? Are you interested in monetizing open-source development? Do you have any suggestions? Concerns?

Would be glad to receive any feeedback. Thank you for attention.

### CODE REVIEW

**Comment by PatchRanger** [comment]
@OskarStark @jordisala1991 Ok, thank you for quick & clear response.

**Comment by greg0ire** [comment]
>     Please review whether it correponds to your vision of the open-source development

It certainly doesn't

**Comment by Soullivaneuh** [comment]
We are not interesting, open-source project should be paid at all.

Plus, your plugin give the possibility to pay us a download we don't handle, but GitHub does. Even if GitHub might not need this money, this is not fair at all.

Regards.

**Comment by greg0ire** [comment]
@Soullivaneuh `*interested` :P I think we are really interesting. See https://github.com/Free2Wait/composer-free2wait/issues/6

**Pull request closed without merging**
