### PR TITLE
(PHPCR) Fix PSR naming of PHPCR repositories

### PR DESCRIPTION
**Pull request by Peekmo**
Hello,
I changed class names of the PHPCR repositories to be PSR compatible. I was unable to autoload them via composer.
Please, if you accept it, let me know when it will be available as a release.

Thank you,
Regards,
Peekmo

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @sonata-project/phpcr-admin

**Comment by dbu** [comment]
ups. yeah, that makes sense, no idea how that could ever have worked. fine for me to merge. what is about the sandbox ci failures? are they relevant?

**Comment by OskarStark** [comment]
thanks for your feedback @dbu 

to be honest, i'm not sure, the travis build is important, but i can't check the sandbox stuff (due to permissions)

**Comment by OskarStark** [comment]
Thank you @Peekmo

**Comment by Peekmo** [comment]
No problem thank you !

**Pull request merged**
