### PR TITLE
Declare conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Declare conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0.

I am targeting this branch, because this change respects BC.

Follow up of #1930.

## Changelog

```markdown
### Added
- Conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0.
```

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by phansys** [comment]
Seems that the branch protection rules are referencing some non existing jobs.

**Comment by wbloszyk** [comment]
> Seems that the branch protection rules are referencing some non existing jobs.

https://github.com/sonata-project/SonataMediaBundle/pull/1944/files

**Review by jordisala1991 — APPROVED** [review]

**Comment by Webonaute** [comment]
Why declaring conflict instead of fixing the conflict? it prevent from upgrading our project.

**Comment by VincentLanglet** [comment]
> Why declaring conflict instead of fixing the conflict? it prevent from upgrading our project.

Declaring the conflict is about telling the truth about the current situation to avoid people upgrading the nelmio api and getting stuck with a non working project.

Fixing the conflict
- does not take the same time than adding the conflict
- is maybe not possible without introducing BC-break.

Feel free to provide a PR ! :)

**Comment by wbloszyk** [comment]
> Why declaring conflict instead of fixing the conflict? it prevent from upgrading our project.

Diffrence between `nelmio/api-doc-bundle` v2, v3 and v4 are huge. Also they are using annotations which force us to provide solution for each version in seperate files. It will be hard to load with dotrine and contribiuting. 

In Sonata4 we want to move API in seperate bundle(s). Then users will be ale to use Sonata solution, third part solution or PWN solution for provide API.

**Comment by VincentLanglet** [comment]
Btw @phansys I'm not sure it works with the V3: https://github.com/sonata-project/SonataMediaBundle/pull/1958

**Pull request merged**
