### PR TITLE
Fix typo on tilleuls/ckeditor-sonata-media-bundle suggestion

### PR DESCRIPTION
**Pull request by volkan**
Closes #

### Changelog

```markdown
### Added
- Added some `Class::newMethod` to do great stuff

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### To do

- [ ] My PR stuff
- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@volkan Thanks for the fix!

But please next time, update your PR body. This is a template that **must** be filled.

**Comment by volkan** [comment]
@Soullivaneuh ok. Thanks.

**Comment by OskarStark** [comment]
I updated the Header

**Comment by Soullivaneuh** [comment]
> I updated the header

@OskarStark No changelog needed for pedantic PRs.

**Pull request merged**
