### PR TITLE
Added gallery list block

### PR DESCRIPTION
**Pull request by core23**
bildschirmfoto 2015-11-25 um 15 26 27

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @core23

**Comment by rande** [comment]
Please do not merge the PR too quickly, headers are missing

**Comment by OskarStark** [comment]
Sorry but travis was green, so no cs error:(

Am Freitag, 27. November 2015 schrieb Thomas :

**Comment by core23** [comment]
Which headers do you mean? @rande

**Pull request merged**
