### PR TITLE
Added russian translations

### PR DESCRIPTION
**Pull request by vyshkant**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added russian translations
```

## Subject

Some keys of russian translation were missing. Some of the keys that were present had stubs instead of translations. Russian translations have been added for both of these cases.

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked by #1337

**Comment by greg0ire** [comment]
Might be not blocked in fact, because no php files were changed

**Comment by vyshkant** [comment]
> Might be not blocked in fact, because no php files were changed

I honestly don't understand how these PRs are related. Should I do rebase?

**Comment by greg0ire** [comment]
My PR fixes the Travis build. Retriggerring a build right now because it will definitely help

**Pull request merged**
