### PR TITLE
Flush whatever of the $andFlush value

### PR DESCRIPTION
**Pull request by Baltox**

### CODE REVIEW

**Comment by Baltox** [comment]
Can someone look at this PR ?

**Comment by greg0ire** [comment]
The commit message subject, which should say what you are doing, is really good. The commit message body, which should explain why you are doing it, is missing. Please fix that.

**Comment by Baltox** [comment]
Ok. 
When i use the `save($media, $andFlush = true)` function, whatever the value of the `$andFlush` attribute, the system already flush db.

**Comment by greg0ire** [comment]
> When i use the save($media, $andFlush = true) function, whatever the value of the $andFlush attribute, the system already flush db. 

That's a great explanation. Please put it in your commit message, maybe in a less informal way.

**Comment by Baltox** [comment]
I can't update the commit msg, i can just update the title of the PR..
Can you merge this PR, it's a bug and i think this affect a lot of people..

**Comment by greg0ire** [comment]
> I can't update the commit msg, i can just update the title of the PR..

Yes you can : 

```
git commit --amend
git push --force
```

**Comment by Baltox** [comment]
It's ok now

**Pull request merged**
