### PR TITLE
added missing use statement

### PR DESCRIPTION
**Pull request by ahmetakbn**
Refs #999

```markdown
### Fixed
- Added missing use statement to `Security/SessionDownloadStrategy.php`
```

### Subject

```php
use Symfony\Component\HttpFoundation\Session\Session;
```
was missing.

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @ahmetakbn 👍

**Comment by OskarStark** [comment]
@greg0ire can you please merge it after travis is green?

**Comment by greg0ire** [comment]
sure

**Comment by greg0ire** [comment]
Wait, we add use statements when they are reference in the phpdoc ?

**Comment by greg0ire** [comment]
I would remove the `getSession` method, instead, and use a local variable.

**Comment by OskarStark** [comment]
i think it is used in the other strategies, too!

**Comment by greg0ire** [comment]
It's private, so no.

**Comment by greg0ire** [comment]
Plus injecting the whole container just for that is probably not the right solution.

**Comment by greg0ire** [comment]
@ahmetakbn, can you please remove the private method? And if you feel like it, fix the huge Law of Demeter violation by injecting `@session` in the class.

**Comment by greg0ire** [comment]
> And if you feel like it, fix the huge Law of Demeter violation by injecting @session in the class.

Actually this should be done in another PR, because of the BC-break.

**Comment by Soullivaneuh** [comment]
> I would remove the getSession method instead, and use a local variable.

Change nothing, you will have to add a PHPDoc for the property.

**Comment by ahmetakbn** [comment]
@greg0ire Changing the injection of container will also change the test. In this case to make it in another PR is better.

**Comment by greg0ire** [comment]
> Change nothing, you will have to add a PHPDoc for the property.

The variable will be local to the only method where it is called, no need for a property.

**Comment by greg0ire** [comment]
@ahmetakbn what about this PR? Should be close it or are you going to remove the private method anyway? Make sure you make the other PR against the master branch, because it will most certainly contain a BC-break.

**Comment by ahmetakbn** [comment]
> @ahmetakbn what about this PR? Should be close it or are you going to remove the private method anyway? Make sure you make the other PR against the master branch, because it will most certainly contain a BC-break.

@greg0ire Yes I will remove the method, will inject the `@session` service and change the test. I am not sure about the BC-break but ok, I will create the PR to master branch. In this case this PR is against 3.x, if you want you can merge this or close.

**Comment by greg0ire** [comment]
I'll close, since you will probably add the type hinting when injecting the dependency.

**Pull request closed without merging**
