### PR TITLE
Address block bundle deprecations

### PR DESCRIPTION
**Pull request by franmomu**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Fixed
- BlockBundle deprecations
```

I did this in a separate PR since I'm not sure about how to deal with the [`buildEditForm`](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Block/GalleryBlockService.php#L110) and [`pre*` methods](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Block/GalleryBlockService.php#L223) since I haven't found yet where they are used. I've seen the [`EditableBlockService`](https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/EditableBlockService.php), but not how to use it.

### CODE REVIEW

**Comment by core23** [comment]
Please add a changelog @franmomu

**Comment by greg0ire** [comment]
@core23 why is this minor?

**Comment by core23** [comment]
> @core23 why is this minor?

Thought we use this for deprecation fixes. Feel free to change the label.

**Comment by greg0ire** [comment]
We use that for new deprecations so that ppl getting a patch release do not get more deprecations, but for fixes, it's patch :)

**Pull request merged**
