### PR TITLE
fixed sync command when using consumer as thumbnail service

### PR DESCRIPTION
**Pull request by toooni**
# Issue with the sync-command
When using `sonata.media.thumbnail.consumer.format` as thumbnail service I recently fixed an issue where the job was sent too early resulting in a race condition. The solution was to postpone firing of the event with the `event_dispatcher` until the event `kernel.finish_request` is thrown.
This resulted in an other issue where the sync command was not working anymore because there is no `kernel.finish_request` event being fired. First I thought that the solution might be to add another listener on the `console.terminate` command. But this would be resulting in a strange behavior of the sync command (The jobs would be published until the command was run completely).
An other issue would have been that the deletion was not made through a notification, but the generation might. This would have been a problem on production environments because of the duration between deleting and creating.

This PR might not be very "sexy" but I really don't know what else to do. I am open to discuss alternatives.

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @rande

**Comment by toooni** [comment]
@OskarStark @rande reminder: the "sonata:media:sync-thumbnails" commend does not work in environments using "sonata.media.thumbnail.consumer.format" until this PR is merged.

**Comment by OskarStark** [comment]
@core23 am i right, that you created the sync command?

**Comment by core23** [comment]
No, the file was created by @pulse00. I fixed the cs on this file.

Have a look at https://github.com/sonata-project/SonataMediaBundle/commits/master/Command/SyncThumbsCommand.php

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by toooni** [comment]
@Soullivaneuh I'll do. I really appreciate your work (very much!!!), but next time I hope you guys aren't implementing something like StyleCI at the same time ;). In my case it's not much work because the code changes are very small. But I would understand if some contributors might be frustrated and won't create a new PR.

**Comment by OskarStark** [comment]
@toooni thank you for resubmitting and reworking your PR!

We hope that we will not have such massive changes in the future ;-)

**Pull request closed without merging**
