### PR TITLE
Properly resolve paramters in application config

### LINKED ISSUE #1271: AddProviderCompilerPass parameter replacement
After the change made by #1218 we no longer have the parameter replacement working in the providers configuration.

For example I use different filesystem for dev/staging/prod and to defined that I used a parameter:

```yaml
providers:
        file:
            filesystem: %sonata_media.filesystem%
```

Now I get an error saying that the service is %sonata_media.filesystem% doesn't exist.

### PR DESCRIPTION
**Pull request by benjaminrau**
I am targeting this branch, because it fixes problems with latest 3.X release.

Closes #1271 

## Changelog
```markdown
### Fixed
- Fixes problem with parameter resolution in extension config
```

### Fixed
Recently the AddCompilerPass was refactored and an ugly hack was removed to resolve paramters in extension config. Now parameters (from parameters.yml) and used in config.yml are no longer replaced. With this PR the parameters are resolved again.

### CODE REVIEW

**Comment by jordisala1991** [comment]
What happens if some of these values is not a parameter?

**Comment by benjaminrau** [comment]
@jordisala1991 It is untouched then. If there is nothing to resolve the method resolveValue is just returning the input value.

**Comment by OskarStark** [comment]
Can you add a test case for both cases?

**Comment by benjaminrau** [comment]
@jordisala1991 I think i would need some assistance or at least somebody pointing to a direction for that

**Comment by OskarStark** [comment]
https://github.com/SymfonyTest/SymfonyDependencyInjectionTest might be a good starting point

**Comment by OskarStark** [comment]
Any news on this @benjaminrau ?

**Pull request closed without merging**
