### PR TITLE
Allow picture element options change from twig function

### LINKED ISSUE #2342: Twig helper function does not set title
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.19.0          4.19.0          The missing Symfony Admin Generator
sonata-project/block-bundle              4.18.0          4.18.0          Symfony SonataBlockBundle
sonata-project/cache                     2.2.0           2.2.0           Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/classification-bundle     4.3.0           4.3.0           Symfony SonataClassificationBundle
sonata-project/doctrine-extensions       1.18.1          2.0.1           Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.8.0           4.8.0           Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/entity-audit-bundle       1.9.0           1.9.0           Audit for Doctrine Entities
sonata-project/exporter                  3.0.0           3.0.0           Lightweight Exporter library
sonata-project/form-extensions           1.18.0          1.18.0          Symfony form extensions
sonata-project/formatter-bundle          5.0.1           5.0.1           Symfony SonataFormatterBundle
sonata-project/media-bundle              4.5.1           4.5.1           Symfony SonataMediaBundle
sonata-project/page-bundle               4.x-dev ac2b373 4.x-dev ac2b373 This bundle provides a Site and Page management through contain...
sonata-project/seo-bundle                3.4.0           3.4.0           Symfony SonataSeoBundle
sonata-project/twig-extensions           2.0.0           2.0.0           Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v5.4.13 v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScri...
symfony/cache                      v5.4.13 v6.1.5  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v2.5.2  v3.1.1  Generic abstractions related to caching
symfony/config                     v5.4.11 v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.4.13 v6.1.6  Eases the creation of beautiful and testable command line interfaces
symfony/debug-bundle               v5.4.11 v6.1.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogComm...
symfony/dependency-injection       v5.4.13 v6.1.5  Allows you to standardize and centralize the way objects are constructed in your appl...
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.13 v6.1.6  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v5.4.5  v6.1.0  Registers environment variables from a .env file
symfony/error-handler              v5.4.11 v6.1.6  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.9  v6.1.0  Provides tools that allow your application components to communicate with each other ...
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.11 v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.13 v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v5.4.11 v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.19.3 v2.2.3  Composer plugin for Symfony
symfony/form                       v5.4.13 v6.1.5  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.13 v6.1.6  Provides a tight integration between Symfony components and the Symfony full-stack fr...
symfony/http-client                v5.4.13 v6.1.6  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.2  v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.13 v6.1.6  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.13 v6.1.6  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.11 v6.1.6  Provides a PHP replacement layer for the C intl extension that includes additional da...
symfony/mailer                     v5.4.13 v6.1.5  Helps sending emails
symfony/maker-bundle               v1.47.0 v1.47.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and m...
symfony/mime                       v5.4.13 v6.1.6  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.10 v6.1.2  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/options-resolver           v5.4.11 v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.11 v6.1.3  Provides password hashing utilities
symfony/polyfill-ctype             v1.26.0 v1.26.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.4.11 v6.1.3  Executes commands in sub-processes
symfony/property-access            v5.4.11 v6.1.3  Provides functions to read and write from/to an object or array using a simple string...
symfony/property-info              v5.4.11 v6.1.6  Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge    v2.1.3  v2.1.3  PSR HTTP message bridge
symfony/routing                    v5.4.11 v6.1.5  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.11 v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack fr...
symfony/security-core              v5.4.13 v6.1.6  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.11 v6.1.0  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.13 v5.4.13 Symfony Security Component - Guard
symfony/security-http              v5.4.13 v6.1.6  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.4.13 v6.1.6  Handles serializing and deserializing data structures, including object graphs, into ...
symfony/service-contracts          v2.5.2  v3.1.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.13 v6.1.5  Provides a way to profile code
symfony/string                     v5.4.13 v6.1.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points an...
symfony/translation                v5.4.12 v6.1.6  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.2  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.12 v6.1.6  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.8  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/ux-turbo                   v2.4.0  v2.4.0  Hotwire Turbo integration for Symfony
symfony/validator                  v5.4.13 v6.1.6  Provides tools to validate values
symfony/var-dumper                 v5.4.13 v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.10 v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v5.4.13 v6.1.6  Provides a development tool that gives detailed information about the execution of an...
symfony/webpack-encore-bundle      v1.15.1 v1.15.1 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.4.12 v6.1.6  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.1.10 (cli) (built: Sep  1 2022 21:43:31) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
```

## Subject
{{ sonata_media(media, 'large', {'picture': ['small', 'big'], 'title': 'This does not work'}) }}
{{ sonata_media(media, 'large', {'srcset': ['small', 'big'], 'title': 'This does work'}) }}

## Actual results
with the `picture` images have their own name as a title.

### PR DESCRIPTION
**Pull request by haivala**
## Subject

I am targeting this branch, because this streamlines twig functions for src.

Closes #2342.

## Changelog

```markdown

### Changed
How `picture` element twig options are merged, making them work same way as `srcset`
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Can you add a test about the change ? This will prevent regressions

**Comment by haivala** [comment]
> Can you add a test about the change ? This will prevent regressions

I would need help to do that. I don't know where to begin

**Comment by VincentLanglet** [comment]
> > Can you add a test about the change ? This will prevent regressions
> 
> I would need help to do that. I don't know where to begin

A unit test need to be added for `getHelperProperties` in this class
https://github.com/sonata-project/SonataMediaBundle/blob/4.x/tests/Provider/ImageProviderTest.php

You wanted to change the way properties are merged.
So if you call `getHelperProperties` with a title, prior to this change the title is not used, and now it will.
Write a test to reproduce the behavior you want
- without your change the test fail
- with your change the test succeed

**Comment by haivala** [comment]
I hope this would not be closed.

**Comment by VincentLanglet** [comment]
> I hope this would not be closed.

Feel free to finish it. PR with 6 months inactivity are automatically closed.

**Pull request merged**
