### PR TITLE
allow PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Added support for PHP 8.x
 ```

### CODE REVIEW

**Comment by Yozhef** [comment]
Problem 1  fixed in the master branch in version 3.0 DataGritBunble  - https://github.com/sonata-project/SonataMediaBundle/pull/1907

**Comment by Yozhef** [comment]
Problem 2 - waiting release - https://packagist.org/packages/liip/imagine-bundle#2.x-dev

**Comment by JustDylan23** [comment]
@Yozhef A new version has been release that supports PHP 8

**Comment by VincentLanglet** [comment]
You need to rebase 3.x in order to fix some tests

**Comment by Yozhef** [comment]
@VincentLanglet yes sure but tomorrow, today is a busy day sorry.

**Comment by Yozhef** [comment]
Waiting support php 8.0 -> sonata-project/doctrine-orm-admin-bundle

**Comment by VincentLanglet** [comment]
> Waiting support php 8.0 -> sonata-project/doctrine-orm-admin-bundle

Blocked by auditEntityBundle ; but now it's a sonata project repository
https://github.com/sonata-project/EntityAuditBundle

**Comment by Yozhef** [comment]
@VincentLanglet synchronized =)

**Comment by jordisala1991** [comment]
It needs a release for notification bundle

**Comment by jordisala1991** [comment]
And it will be blocked by this other package to: https://packagist.org/packages/kriswallsmith/buzz#v0.16.0

the latest 1.x release allows php 8 tho

**Comment by wbloszyk** [comment]
@Yozhef 
To finish this PR you should add support for buzz 1.x or move it to the master branch where buzz will be removed.

IMO you should move it to the master. I have prepared drop support for buzz and I will push it in Monday.

CAn you do it?

**Comment by Yozhef** [comment]
@wbloszyk moved to the master - I will be grateful for help, unfortunately, not much free time at the moment - but as soon as it appears ready to take on tasks with TODO

**Comment by phansys** [comment]
Tests are passing now :tada:

**Comment by jordisala1991** [comment]
You can move it to 3.x, because of this (and we need to discuss it if we want to give it support):

It is installing kriswallsmith/buzz ^0.15, because that older version supports php > 5.3. On ^0.16 the requirement was changed to ^5.6 || ^7.0.

I am not sure it will work with 0.15, but as far as composer requirements it works. (If we accept this, we should move it to 3.x because it will pass too).

**Comment by Yozhef** [comment]
@jordisala1991 sorry for the long reaction changed to 3.x

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by wbloszyk** [comment]
Thank you @Yozhef

**Comment by VincentLanglet** [comment]
There is some issue with the changelog detection of this pr: https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/next-release/media-bundle

**Pull request merged**
