### PR TITLE
Remove 'wrap' property from GalleryBlock

### PR DESCRIPTION
**Pull request by core23**
### Changelog

```markdown
### Removed
 * Removed `wrap` property from `GalleryBlockService`
```

### Subject
Removes an unused property form `GalleryBlockService`.

### To do

- [x] Add an upgrade note

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @core23 , but then we have to deprecate this, right?

And we need an UPGRADE notice in this PR please

**Comment by core23** [comment]
Yes, but I have no idea how to add a deprection notice for BlockServices.

I'll add an UPGRADE info, when 3.0 is scheduled.

**Comment by OskarStark** [comment]
ping @rande

**Comment by rande** [comment]
This option can be used by some people which extend the template

**Comment by OskarStark** [comment]
@core23 can you rebase please?

**Comment by OskarStark** [comment]
ping @core23

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by OskarStark** [comment]
can you please add the default PR header?

**Comment by core23** [comment]
Done @OskarStark

**Comment by OskarStark** [comment]
Thank you @core23 👍

**Pull request merged**
