### PR TITLE
Sonata\AdminBundle\Validator\ErrorElement do not exist

### PR DESCRIPTION
**Pull request by mathieu-axiocode**
I think this should be correct. Or just remove the validateBlock function...

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you please provide test that reveal this error?

**Comment by mathieu-axiocode** [comment]
I am just trying to combine media bundle, page bundle and block bundle. I just did the install of mediabundle and when loading a media block i get this error while an ajax request : 
**Compile Error: Declaration of Application\Sonata\MediaBundle\Block\GalleryBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)**
That's why I've proposed this PR. 
I extended the service and changed AdminBundle for CoreBundle and it works.

Now I'm getting another error when trying to load a media from from a gallery block : 
**Runtime Notice: Declaration of Sonata\MediaBundle\Controller\GalleryAdminController::render() should be compatible with Sonata\AdminBundle\Controller\CRUDController::render($view, array $parameters = Array, Symfony\Component\HttpFoundation\Response $response = NULL, Symfony\Component\HttpFoundation\Request $request = NULL)**

Sorry for my english ;-)

**Comment by Soullivaneuh** [comment]
Thanks for explanation.

By tests, I mean unit tests cases! ;-)

**Comment by mathieu-axiocode** [comment]
Sorry, not yet in my skills...

**Comment by Uriziel** [comment]
Isn't this actually problem with improperly set up composer.json, trying to couple incompatible versions of bundles?

**Comment by NeuralClone** [comment]
I'm pretty sure I've had a similar problem as well. I've had some difficulty getting some of these bundles working together due to dependency issues, and this error seems _very_ familiar. Finding that right combination can be a bit of a headache, especially if you want to use a lot of them.

Do you think can provide the exact versions of the Sonata bundles you're using (as well as the relevant config files), @mathieu-axiocode? I might be able to contribute some tests to help isolate this if I can reproduce the error. :)

(Also, your English is fine. :+1: )

**Comment by phansys** [comment]
I think [this build](https://travis-ci.org/sonata-project/SonataMediaBundle/jobs/69225336#L403) can be considered a test for this issue.

**Comment by OskarStark** [comment]
this should be already fixxed in the master branch, or?

this PR is provided against the 2.3 stable...

**Comment by Soullivaneuh** [comment]
cc @rande

**Pull request closed without merging**
