### PR TITLE
updated translation file for media widget

### PR DESCRIPTION
**Pull request by OskarStark**
Refs #849

### CODE REVIEW

**Comment by rande** [comment]
Can you add the missing keys for other translations files ?

**Comment by OskarStark** [comment]
yes, what is the translation then?

the key itself?

**Comment by rande** [comment]
yes, the key itself

**Comment by OskarStark** [comment]
done @rande 

btw. i would like to change ```no_linked_media``` to ```widget.no_linked_media``` 

is that allowed?

**Comment by rande** [comment]
it is important to keep translation keep concistency. So just compare with the rest of the file. the dot notation is used by the admin translation key generation.

**Comment by OskarStark** [comment]
ok, shall i rename to ```widget_context```instead of ```widget.labeLcontext```?

**Comment by rande** [comment]
@OskarStark yes it will be better as the widget is not *only* used for the Admin

**Comment by OskarStark** [comment]
i'll do

**Comment by OskarStark** [comment]
done @rande

**Comment by OskarStark** [comment]
Thank you @rande

**Pull request merged**
