### PR TITLE
Fix broken build

### LINKED ISSUE #930: Documentation is broken
Build is not passing, because something is wrong with sphinx

see sphinx-doc/sphinx#2264

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #930

### CODE REVIEW

**Comment by greg0ire** [comment]
Look this one closely, there are some controversial things in it.

**Comment by greg0ire** [comment]
Looks like there are non-doc issues too…

**Comment by OskarStark** [comment]
but i think we can merge this anyway, what do you think?
Can you please squash your commits?

Thank you!!

**Comment by greg0ire** [comment]
I don't know why you want me to squash my beautiful, independent commits into a big one. I grouped the related commits together so there are now 2 commits instead of 4. Is it about disk space?

**Comment by core23** [comment]
Because every fix or feature should seen as an atomic change in the code. This will keep the history clean.

See: https://github.com/sonata-project/SonataAdminBundle/blob/master/CONTRIBUTING.md#sending-a-pull-request

**Comment by greg0ire** [comment]
I'm fixing two different things here : should I make 2 PRs ?

**Comment by core23** [comment]
Which two things are you fixing? IMO you are fixing https://github.com/sonata-project/SonataMediaBundle/issues/930 which is one concrete bug.

**Comment by greg0ire** [comment]
I'm fixing #930 , and I'm adding a missing newline at the end of a file, but #930 would be fixed without that cs commit. It's just that I saw that issue on the way, and ship it in this PR.

**Comment by core23** [comment]
IMO in this case you can combine these things into one commit.

**Comment by greg0ire** [comment]
I beg to disagree. Imagine you want to make a fix on a file that uses tabs instead of spaces. First thing you do, you change tabs to spaces, and commit that, and then work on your fix. The diff of your fix stays clean, while the diff of a squash of both commits would be quite hard to read. Plus, one can revert one commit and not the other, just in case your fix turns out to be not so good (it happens). Of course you could make two PRs, but they would be conflicting with each other, and the change from tabs to space does not really warrant a PR, does it?

**Comment by greg0ire** [comment]
I think we should fix this first : https://github.com/sonata-project/SonataAdminBundle/pull/3563

**Comment by rande** [comment]
@greg0ire just squash your commit please ;) one PR = one commit, easier to revert ;)

**Comment by greg0ire** [comment]
The PR is about my first commit, the second one is CS, it is something else (and could be in another PRà If my first commit turns out to be bad, you can simply revert the first commit. And just let the cs commit stay. But your repo, your rules… I guess I'll just **remove** my commit from the PR if no one wants to humor me on this.

**Comment by greg0ire** [comment]
BTW @rande : what about the ACL problem? I summed it up [here](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/357). It is one of the reasons why the build still fails.

**Pull request merged**
