### PR TITLE
Update kriswallsmith/buzz

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Update
- update kriswallsmith/buzz deps
 ```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Can it be done on the stable branch instead ?

And tests are failing

**Comment by Yozhef** [comment]
@VincentLanglet At first glance, no. But as soon as I have more time I will try to look into more detail

**Comment by phansys** [comment]
As you can see in the [changelog](https://github.com/kriswallsmith/Buzz/blob/master/CHANGELOG.md#change-log), there are some BC breaks between version `1.x` and `0.x`.

**Comment by jordisala1991** [comment]
IMHO there is no point on upgrading this on master, it was deprecated in favor of symfony http-client

**Comment by phansys** [comment]
Thank you @Yozhef!
If you want. you can work on replacing `kriswallsmith/buzz` with `symfony/http-client` in order to address #951.

**Pull request closed without merging**
