### PR TITLE
Fix PHPCR base class names

### PR DESCRIPTION
**Pull request by mmenozzi**

### CODE REVIEW

**Comment by OskarStark** [comment]
@mmenozzi can you please rebase this PR?

thank you :+1:

**Comment by mmenozzi** [comment]
Hi @OskarStark,
models class names have already been fixed by @Soullivaneuh with this monster commit https://github.com/sonata-project/SonataMediaBundle/commit/8335b04566221d5da43a307ac58f4c0d5fe1aca4 so I think that you can close this PR.

**Comment by core23** [comment]
You're right. Thank you

**Comment by OskarStark** [comment]
thanks for the feedback @mmenozzi

**Comment by mmenozzi** [comment]
@OskarStark @core23 you're welcome guys!

**Pull request closed without merging**
