### PR TITLE
Resolve config parameters before returning config.

### PR DESCRIPTION
**Pull request by supersmile2009**
I am targeting this branch, because this is backwards compatible bug fix.

## Changelog
```markdown
### Fixed
- Bug where an extension config with unresolved parameters was processed in a compiler pass
```

## Subject
Unresolved config was processed in `AddProviderCompilerPass`. If some config value wasn't set directly, but `'%parameter%'` was passed, this parameter value wasn't properly resolved and was processed as `'%parameter%'` string. This led to issues particularly when using parameter to set formats in a context. Configuration expected formats value to be an array, but since parameter was not resolved, it was actually a string and processing configuration failed.

### CODE REVIEW

**Comment by covex-nn** [comment]
I reproduced a bug with the following configuration:

```yaml
parameters:
    media_formats:
        small: { width: 100 , quality: 70}
        big:   { width: 500 , quality: 70}

sonata_media:
    default_context: default
    contexts:
        default:
            formats: '%media_formats%'
```

This PR fixes it

**Comment by OskarStark** [comment]
Thank you @covex-nn, good job 👍

**Comment by Webonaute** [comment]
@supersmile2009 is working on it. it will be available soon. sorry for the delay, we got others priorities.

**Comment by supersmile2009** [comment]
Hi @OskarStark.
Sorry, I didn't have time for it earlier.
I added a test. Waiting for your review :)

**Comment by OskarStark** [comment]
Thank you @supersmile2009 👍

**Pull request merged**
