### PR TITLE
minor documentation rst link format fix

### PR DESCRIPTION
**Pull request by mcwebb**
fix broken link formatting

### CODE REVIEW

**Comment by OskarStark** [comment]
After travis is green, this can be merged :+1:

**Comment by mcwebb** [comment]
The travis tests seem to be failing because of a bad Composer command, doesn't seem to be anything to do with the PR.
What should I do?

**Comment by OskarStark** [comment]
Thank you @mcwebb you are right :+1:

**Comment by mcwebb** [comment]
:+1:

**Pull request merged**
