### PR TITLE
Fix media widget spanish translations

### PR DESCRIPTION
**Pull request by asenor**
I am targetting this branch, because this is a translation improvement.

## Changelog

```markdown
### Fixed
- Fixed media widget spanish translations
```

## Subject

This fixes media widget spanish translations.

### CODE REVIEW

**Comment by OskarStark** [comment]
minor or patch? @Soullivaneuh @greg0ire 

LGTM 👍

**Comment by greg0ire** [comment]
I'd lean towards patch, but this is kind of a grey area.

**Comment by Soullivaneuh** [comment]
Agreed, it's a gray area.

But as we do not support minor branches, I think make it on a patch is a better idea.

**Comment by greg0ire** [comment]
> Agreed, it's a gray area.

Just like the spelling of [gr[ae]y](http://grammarist.com/spelling/gray-grey/)

**Comment by OskarStark** [comment]
Thank you @asenor 👍

**Comment by asenor** [comment]
You're welcome :smile:

**Pull request merged**
