### PR TITLE
Remove Buzz dependency and replace it with guzzle

### LINKED ISSUE #951: Replace Buzz with PSR http-client
Refs https://github.com/sonata-project/SonataMediaBundle/issues/910

Today we are using both bundles for http connections. IMO we should drop Buzz and Guzzle and use the PSR http-client.

### PR DESCRIPTION
**Pull request by core23**
Closes #951

### Changelog

```markdown
### Changed
- Removed `buzz` dependency and replaced it with `GuzzleHttp`
```

### Subject

Today we use both dependencies for http connection. This change removed the buzz dependency completly. This shouldn't be done with a BC, because we had to load both to stay BC.

### To do

- [X] Update the tests
- [X] Add an upgrade note

### CODE REVIEW

**Comment by core23** [comment]
We need php >=5.5 for this

**Comment by greg0ire** [comment]
We should really consider using http://httplug.io/ cc @dbu

**Comment by core23** [comment]
Should we use `HTTPlug` and suggest a `guzzle6-adapter` @sonata-project/contributors

**Comment by dbu** [comment]
glad to help with httplug if you need, i think it would make sense to use it.

**Comment by core23** [comment]
Closed in favor of https://github.com/sonata-project/SonataMediaBundle/pull/1060

**Pull request closed without merging**
