### PR TITLE
Fix deprecated FormType::setDefaultOptions usage

### LINKED ISSUE #784: DEPRECATED - FormTypeInterface::setDefaultOptions()
Hello.

I am updated my project from symfony 2.6 to 2.7 and after update i received this deprecated message:

DEPRECATED - Sonata\MediaBundle\Form\Type\MediaType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0. DEPRECATED - Sonata\MediaBundle\Form\Type\MediaType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #784

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@rande This is php change now. What is your excuse? :-)

**Comment by rande** [comment]
@Soullivaneuh I trust you ;)

**Comment by rande** [comment]
and it is friday

**Comment by Soullivaneuh** [comment]
Yeah and I'll add that testing is doubting in that way! :-)

**Pull request merged**
