### PR TITLE
mass media from path command

### PR DESCRIPTION
**Pull request by nicolasricci**
This new command line task allows you to import mass medias from a specific folder location, with a specific context (optional) and in a specific gallery (optional)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by OskarStark** [comment]
can you please resubmit this to 3.x @nicolasricci ?

**Comment by OskarStark** [comment]
@nicolasricci can you please resubmit this to 3.x

**Comment by nicolasricci** [comment]
@OskarStark i will have a quick look today if I can because some of the code done almost 3 years ago might be out-of-date. keep you posted

**Comment by nicolasricci** [comment]
@OskarStark as expected it requires a bit more work than only resubmitting to 3.x.
I keep this on my todo list for later on as it would also require some documentation and unit tests.

**Comment by OskarStark** [comment]
A collegue of mine started to implement multi upload for the browser, too
https://github.com/sonata-project/SonataMediaBundle/pull/1105

you can have a look here, too

**Pull request closed without merging**
