### PR TITLE
chore: migration symfony 7

### PR DESCRIPTION
**Pull request by pauljosephkrogulec**
## allowing support of Symfony  7

I am targeting this branch, because is for allowing the possibility of use in symfony 7 project and don't create a BC-break

## Changelog

Allowing support of Symfony 7  (@pauljosephkrogulec)

```markdown
### Added
- Support of Symfony 7

### Changed

### Deprecated

### Removed

### Fixed

### Security
```
## TODO
Need to merge [this](https://github.com/sonata-project/form-extensions/pull/462) before merging this PR

### CODE REVIEW

**Comment by VincentLanglet** [comment]
You need to add the same entry in the CI to check SF7 is installed correctly.

Also, we will need to add support for those lib first: https://github.com/sonata-project/SonataMediaBundle/blob/4.x/composer.json#L88-L91

**Comment by VincentLanglet** [comment]
> Also, we will need to add support for those lib first: [`4.x`/composer.json#L88-L91](https://github.com/sonata-project/SonataMediaBundle/blob/4.x/composer.json?rgh-link-date=2023-11-23T20%3A50%3A11Z#L88-L91)

I added support for SF7 on
- SonataBlockBundle
- SonataAdminBundle

For SonataDoctrineORMAdminBundle we need AuditBundle which need the DoctrineExtensions
For ClassificationBundle we need SonataDoctrineORMAdminBundle

**Comment by phansys** [comment]
Thank you for taking care of this @pauljosephkrogulec.
Please, let us know if you need help finishing this job.

**Comment by phansys** [comment]
Closing in favor of #2430.
Thank you!

**Pull request closed without merging**
