### PR TITLE
Use validator in CoreBundle

### LINKED ISSUE #680: Validation depend to AdminBundle
Hello, 

I'm not use AdminBundle. So I have an error

```
Attempted to load class "InlineConstraint" from namespace "Symfony\Component\Validator\Constraints\Sonata\AdminBundle\Validator\Constraints".
Did you forget a "use" statement for another namespace?

```

see https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/validation.xml#L13

### PR DESCRIPTION
**Pull request by Shine-neko**

### CODE REVIEW

**Comment by Shine-neko** [comment]
@rande Is it OK ?

**Comment by rande** [comment]
@Shine-neko first you need to fix the CoreBundle by creating the ``sonata.core.validator.inline` service

**Comment by Shine-neko** [comment]
@rande now what ?  :D

**Comment by Shine-neko** [comment]
@rande is it OK for you ?

**Comment by rande** [comment]
@Shine-neko not yet actually, this will create a major BC break in others bundles.

**Comment by rande** [comment]
Sonata's bundles now use the ErrorElement from the CoreBundle.

**Pull request closed without merging**
