### PR TITLE
Increase Psalm to level 2

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this can't be done on 3.x.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Maybe @VincentLanglet you can help me with the one issue I don't know how to fix:

```
ERROR: DocblockTypeContradiction - src/Thumbnail/FormatThumbnail.php:132:14 - Docblock-defined type array<array-key, string> for $formats is always array (see https://psalm.dev/155)
        if (!\is_array($formats)) {
```

The docblock says `array|string|null` but since it is not enforced by a native typehint I have this final check.

**Comment by VincentLanglet** [comment]
> Maybe @VincentLanglet you can help me with the one issue I don't know how to fix:
> 
> ```
> ERROR: DocblockTypeContradiction - src/Thumbnail/FormatThumbnail.php:132:14 - Docblock-defined type array<array-key, string> for $formats is always array (see https://psalm.dev/155)
>         if (!\is_array($formats)) {
> ```
> 
> The docblock says `array|string|null` but since it is not enforced by a native typehint I have this final check.

Sure

Phpstan has a `treatPhpdocAsCertain: false` option. But Psalm doesn't.
See https://github.com/vimeo/psalm/issues/5643

I see multiple solutions:
- relying on the phpdoc and changing too 
```
if (null === $formats) {
     $formats = array_keys($provider->getFormats());
} elseif (!\is_array($formats)) {
      $formats = [$formats];
}
```
- globally ignoring `DocblockTypeContradiction` and `RedundantConditionGivenDocblockType` on our project because it could be considered as the equal as `treatPhpdocAsCertain: false`. This is what I do at work.
- adding a psalm-suppress
- adding to baseline with a comment

**Comment by jordisala1991** [comment]
> * globally ignoring DocblockTypeContradiction and RedundantConditionGivenDocblockType on our project because it could be considered as the equal as treatPhpdocAsCertain: false. This is what I do at work.


I followed the strategy to ignore those errors globally.

**Comment by VincentLanglet** [comment]
> > * globally ignoring DocblockTypeContradiction and RedundantConditionGivenDocblockType on our project because it could be considered as the equal as treatPhpdocAsCertain: false. This is what I do at work.
> 
> I followed the strategy to ignore those errors globally.

Can you add a comment ? For instance in my project I have:
```
<!-- Psalm equivalent of PHPStan config `treatPhpDocTypesAsCertain: false` -->
```

**Comment by jordisala1991** [comment]
Added comment.

**Review by VincentLanglet — APPROVED** [review]

**Review by franmomu — APPROVED** [review]

**Comment by jordisala1991** [comment]
So psalm done here, level 1 is impossible to reach, more than 800 errors raised.

**Pull request merged**
