### PR TITLE
Replaced form types for the FQCN's

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Changed
- Replaced form types for the FQCN's
```

## To do

- [x] Finish replacements
- [x] Update the tests

## Subject

Trying to make SF3 work with this bundle. I think this is mandatory for SF3, am I wrong? Because I get a lot of deprecations in SF2.8.
Is there a way, or it is implemented in another way in other sonata bundles to avoid all this code?
Also, do I need to replace DataGridMapper types and ListMapper types?

### CODE REVIEW

**Comment by greg0ire** [comment]
> Trying to make SF3 work with this bundle. I think this is mandatory for SF3, am I wrong?

Nope
you're goddamn right

**Comment by jordisala1991** [comment]
Replacements are done I believe.

Do you think we need to test all of the replacements?

**Comment by greg0ire** [comment]
> Do you think we need to test all of the replacements?

I think we can't reasonly ask you to test all this, especially if there were no tests in the first place (are there any?). So do test some, but don't feel obliged to test all of them.

**Comment by jordisala1991** [comment]
I added all the test classes for the ones that I did modify. I didn't test all of them, but atleast now should be easier to add new ones. 

Let's see travis

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataDatagridBundle/pull/45

This might be related to tests failing, not sure what is wrong tho..

Do you have any idea @greg0ire ?

**Comment by greg0ire** [comment]
Sorry I was away... looks like you fixed it?

**Comment by jordisala1991** [comment]
Well, I added datagrid-bundle 2.2.1 to the conflicts section of composer.json. Not sure if it is something that we can fix here or it has to be fixed on datagrid-bundle.

**Comment by greg0ire** [comment]
I'll have a look at it tomorrow

**Comment by jordisala1991** [comment]
There is no bug at all, the test are just missing to mock getRootAliases... will fix it tomorrow

**Comment by jordisala1991** [comment]
Rebased, now it works. Coverage +2.6% 🎉

**Comment by jordisala1991** [comment]
Did a little refactor to change:

`public function setUp()` to `protected function setUp()`

**Comment by jordisala1991** [comment]
Changed from protected to private on test properties, also added some that were missing. 

Based on https://github.com/sonata-project/SonataMediaBundle/pull/1196#discussion_r100697487

**Comment by greg0ire** [comment]
@sonata-project/contributors , please review

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !

**Comment by OskarStark** [comment]
Great job @jordisala1991 👍 🍻

**Pull request merged**
