### PR TITLE
PHPCR Fixes to make it work

### PR DESCRIPTION
**Pull request by robhunt3r**
Changes are basically correcting PHPCR mapping files, commenting method in BaseGallery which was causing troubles (we need to take a look to it) and correct wrong class names in repositories.

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @robhunt3r

**Comment by robhunt3r** [comment]
Wow I totally forgot about this, I will check everything tomorrow at work, now it's late :P @OskarStark @dbu

**Comment by OskarStark** [comment]
thank you @robhunt3r :+1:

**Comment by robhunt3r** [comment]
@OskarStark It should be OK now, please review and give me feedback, it's been a long time and I don't remember so much about this PR ^^'

**Comment by OskarStark** [comment]
@robhunt3r can you please rebase, i think the travis errors are already fixed in the master branch, thank you!

**Comment by robhunt3r** [comment]
@OskarStark I've rebased on usptream master, check it out, I usually mess up things with github -_- :-1:

**Comment by OskarStark** [comment]
thank you

@lsmith77 @dbu can you please review this PR?

**Comment by dbu** [comment]
it looks sane to me. the build failures look like an issue with symfony 3 compatibilty and unrelated to this PR.

**Comment by OskarStark** [comment]
ok, lets merge it as it is,

thank you guys :+1:

**Comment by robhunt3r** [comment]
Glad to help, even so late I forget about this :P :+1:

**Comment by OskarStark** [comment]
:+1:

**Pull request merged**
