### PR TITLE
Proper config for gallery manager

### PR DESCRIPTION
**Pull request by renooo**
Change config for the service **sonata.media.manager.gallery** according to the constructor here :
https://github.com/sonata-project/SonataCoreBundle/blob/master/Model/BaseManager.php#L40

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
It would be BC break, wouldn't be?

**Comment by renooo** [comment]
I'm not sure, @Soullivaneuh

If you look the config for **doctrine_orm** (https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/doctrine_orm.xml#L19), it works fine.

But this constructor 
https://github.com/sonata-project/SonataCoreBundle/blob/master/Model/BaseManager.php#L40
is not happy when you're using **doctrine_phpcr** and **doctrine_mongodb**, until you change these values.

**Comment by OskarStark** [comment]
i think not @Soullivaneuh because before it didn't worked, as the placeholder was wrong

IMO its a bug and should be fixxed with this PR

@rande what do you mean?

**Comment by Soullivaneuh** [comment]
If it's a bugfix, it should be proposed agains last stable branch (2.3).

**Comment by renooo** [comment]
OK, I'll make the PR in the right branch.

**Pull request closed without merging**
